### ISSUE TITLE
译文笔误报告

### ISSUE THREAD

**Issue by gfgafn** [suhanyujie/article-transfer-rs#12]
这行末尾应该是：三次调用 `f.write()` 方法会产生**三次** `write()` 系统调用。 

https://github.com/suhanyujie/article-transfer-rs/blob/0005ba5af7b2d3ccdfe8576ad83eb27d6f7bc873/src/2021/7.unbuffered-io-slows-rust-programs.md?plain=1#L22

**Comment by suhanyujie** [comment]
> 

好的，谢谢指正
